env:
  global:
    - CC_TEST_REPORTER_ID=955c865dd9a017cb598c32abc41566090a54dc70cc7ba903b6140fb17fa3d2fb
language: node_js
node_js:
  - node
sudo: false
cache: npm
matrix:
  fast_finish: true
script: npm run test:coverage
after_install: npm run postinstall
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT